BasicWebsite/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasicWebsite.Models;

namespace BasicWebsite.Areas.Admin.Controllers
{
    public class CompanyController : Controller
    {
        private BasicWebDbContext db = new BasicWebDbContext();

        // GET: /Admin/Company/
        public ActionResult Index()
        {
            return View(db.CompanyModels.ToList());
        }

        // GET: /Admin/Company/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyModel companymodel = db.CompanyModels.Find(id);
            if (companymodel == null)
            {
                return HttpNotFound();
            }
            return View(companymodel);
        }

        // GET: /Admin/Company/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Admin/Company/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Name,StockId,Founded,Director,Country,Headquarters,Description,Tags,IsActive")] CompanyModel companymodel)
        {
            if (ModelState.IsValid)
            {
                db.CompanyModels.Add(companymodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(companymodel);
        }

        // GET: /Admin/Company/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyModel companymodel = db.CompanyModels.Find(id);
            if (companymodel == null)
            {
                return HttpNotFound();
            }
            return View(companymodel);
        }

        // POST: /Admin/Company/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Name,StockId,Founded,Director,Country,Headquarters,Description,Tags,IsActive")] CompanyModel companymodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companymodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(companymodel);
        }

        // GET: /Admin/Company/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyModel companymodel = db.CompanyModels.Find(id);
            if (companymodel == null)
            {
                return HttpNotFound();
            }
            return View(companymodel);
        }

        // POST: /Admin/Company/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompanyModel companymodel = db.CompanyModels.Find(id);
            db.CompanyModels.Remove(companymodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BasicWebsite/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BasicWebsite.Areas.Admin.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        //
        // GET: /Admin/Dashboard/
        [Authorize(Roles="admin")]
        public ActionResult Index()
        {
            return View();
        }
	}
}

BasicWebsite/Areas/Admin/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasicWebsite.Models;
using System.Web.Configuration;

namespace BasicWebsite.Areas.Admin.Controllers
{
    public class EventController : Controller
    {
        private BasicWebDbContext db = new BasicWebDbContext();

        // GET: /Admin/Event/
        public ActionResult Index()
        {
            return View(db.EvenModels.ToList());
        }

        // GET: /Admin/Event/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventModel eventmodel = db.EvenModels.Find(id);
            if (eventmodel == null)
            {
                return HttpNotFound();
            }
            return View(eventmodel);
        }

        // GET: /Admin/Event/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Admin/Event/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Created,CreatedBy,Modified,ModifiedBy,Status,Title,Organizer,Type,StartDate,EndDate,Description")] EventModel eventmodel)
        {
            if (ModelState.IsValid)
            {
                eventmodel.Created = eventmodel.Modified = DateTime.Now;
                eventmodel.CreatedBy = eventmodel.ModifiedBy = User.Identity.Name;
                eventmodel.Status = "Open";
                db.EvenModels.Add(eventmodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eventmodel);
        }

        // GET: /Admin/Event/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventModel eventmodel = db.EvenModels.Find(id);
            if (eventmodel == null)
            {
                return HttpNotFound();
            }
            return View(eventmodel);
        }

        // POST: /Admin/Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Created,CreatedBy,Modified,ModifiedBy,Status,Title,Organizer,Type,StartDate,EndDate,Description")] EventModel eventmodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventmodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventmodel);
        }

        // GET: /Admin/Event/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventModel eventmodel = db.EvenModels.Find(id);
            if (eventmodel == null)
            {
                return HttpNotFound();
            }
            return View(eventmodel);
        }

        // POST: /Admin/Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventModel eventmodel = db.EvenModels.Find(id);
            db.EvenModels.Remove(eventmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult GetAllEvent(string date)
        {
            var currentDate = Convert.ToDateTime(date);
            var applicationUrl = WebConfigurationManager.AppSettings["application-url"];
            var allEvent = db.EvenModels.Where(e => (e.StartDate.Month.Equals(currentDate.Month)
                                              && e.StartDate.Year.Equals(currentDate.Year))
                                              || (e.EndDate.Month.Equals(currentDate.Month)
                                              && e.EndDate.Year.Equals(currentDate.Year)));
            return Json(allEvent.ToList().Select(e => new {
                                                    title=e.Title,
                                                    status=e.Status,
                                                    organizer = e.Organizer,
                                                    start=Convert.ToDateTime(e.StartDate).ToString("yyyy-MM-ddThh:mm:ss"),
                                                    end = Convert.ToDateTime(e.EndDate).ToString("yyyy-MM-ddThh:mm:ss"),
                                                    description = e.Description,
                                                    url=string.Format("{0}/Admin/Event/Details/{1}",applicationUrl,e.ID)
                                                 }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EventList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                var listEvent = new List<EventTable>();
                IQueryable<EventModel> events;
                var sord = string.Empty;
                var order = string.Empty;
                if (!string.IsNullOrEmpty(jtSorting))
                {
                    sord = jtSorting.Split(' ')[0];
                    order = jtSorting.Split(' ')[1];
                    if (order.Equals("ASC"))
                    {
                        switch (sord)
                        {
                            case "Title":
                                events = db.EvenModels.OrderBy(e => e.Title).Skip(jtStartIndex).Take(jtPageSize);
                                break;
                            case "Organizer":
                                events = db.EvenModels.OrderBy(e => e.Organizer).Skip(jtStartIndex).Take(jtPageSize);
                                break;
                            case "Type":
                                events = db.EvenModels.OrderBy(e => e.Type).Skip(jtStartIndex).Take(jtPageSize);
                                break;
                            default:
                                events = db.EvenModels.OrderBy(e => e.ID).Skip(jtStartIndex).Take(jtPageSize);
                                break;

                        }
                    }
                    else
                    {
                        switch (sord)
                        {
                            case "Title":
                                events = db.EvenModels.OrderByDescending(e => e.Title).Skip(jtStartIndex).Take(jtPageSize);
                                break;
                            case "Organizer":
                                events = db.EvenModels.OrderByDescending(e => e.Organizer).Skip(jtStartIndex).Take(jtPageSize);
                                break;
                            case "Type":
                                events = db.EvenModels.OrderByDescending(e => e.Type).Skip(jtStartIndex).Take(jtPageSize);
                                break;
                            default:
                                events = db.EvenModels.OrderByDescending(e => e.ID).Skip(jtStartIndex).Take(jtPageSize);
                                break;

                        }
                    }
                }
                else
                {
                    events = db.EvenModels.OrderBy(e => e.ID).Skip(jtStartIndex).Take(jtPageSize);
                }
                listEvent = events.Select(e => new EventTable
                {
                    ID=e.ID.ToString(),
                    Title=e.Title,
                    Organizer=e.Organizer,
                    Type=e.Type
                }).ToList();
                int eventCount = db.EvenModels.ToList().Count();
                return Json(new { Result = "OK", Records = listEvent, TotalRecordCount = eventCount });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        } 

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

    public class EventTable
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Organizer { get; set; }
        public string Type { get; set; }
    }
}

BasicWebsite/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/calendar")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Dashboard</a></li>
                    <li><a href="#">Settings</a></li>
                    <li class="active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome, @User.Identity.Name !<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#" id="logOff">Log Off</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        @Html.Partial("_SideBar")
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            @RenderBody()
         </div>
    </div>
    <div style="display:none;">
        @Html.BeginForm("LogOff","Account",new{area="Admin"},FormMethod.Post)
        {
            @Html.AntiForgeryToken()
            <input type="submit" id="btnLogOff" />
        }
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jtable")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/calendar")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $('#logOff').click(function () {
                $('#btnLogOff').trigger('click');
            });

            function htmlEncode(value) {
                //create a in-memory div, set it's inner text(which jQuery automatically encodes)
                //then grab the encoded contents back out.  The div never exists on the page.
                return $('<div/>').text(value).html();
            }

            function htmlDecode(value) {
                return $('<div/>').html(value).text();
            }
        });
    </script>
</body>
</html>

BasicWebsite/Areas/Admin/Views/Shared/_SideBar.cshtml
<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li class="sub-header"><strong>Content Manager</strong></li>
        <li><a href=@Url.Action("Index","Company",new{@area="Admin"})>Company</a></li>
        <li><a href=@Url.Action("Index","Dashboard",new{@area="Admin"})>Dashboard</a></li>
        <li><a href="#">Reports</a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href=@Url.Action("Index","Event",new{@area="Admin"})>Event</a></li>
    </ul>
    <ul class="nav nav-sidebar">
        <li class="sub-header"><strong>User Manager</strong></li>
        <li><a href=@Url.Action("AllUsers","Account",new{@area="Admin"})>User</a></li>
        <li><a href=@Url.Action("AllRoles","Account",new{@area="Admin"})>Role</a></li>
    </ul>
</div>
@Scripts.Render("~/bundles/jquery")
<script>
    $(document).ready(function () {
        var menuActive = '@ViewBag.MenuActive';
        if (menuActive != null) {
            $('.sidebar').find('a').each(function () {
                if ($(this).text() == menuActive) {
                    $(this).closest('li').addClass('active');
                }
            });
        }
    });
</script>